//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConexionNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public FUNCIONARIO()
        {
            this.DIA = new HashSet<DIA>();
            this.HORA = new HashSet<HORA>();
            this.ORDEN_PEDIDO = new HashSet<ORDEN_PEDIDO>();
        }
    
        public decimal RUT { get; set; }
        public decimal ID_TIPO { get; set; }
    
        public virtual ICollection<DIA> DIA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual TIPO_FUNCIONARIO TIPO_FUNCIONARIO { get; set; }
        public virtual ICollection<HORA> HORA { get; set; }
        public virtual ICollection<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
    }
}
