//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConexionNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public decimal RUT { get; set; }
        public string DV { get; set; }
        public string P_NOMBRE { get; set; }
        public string S_NOMBRE { get; set; }
        public string P_APELLIDO { get; set; }
        public string S_APELLIDO { get; set; }
        public System.DateTime FECHA_NAC { get; set; }
        public string SEXO { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public decimal ID_COMUNA { get; set; }
        public decimal ID_USUARIO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
