//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORA
    {
        public decimal ID { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public Nullable<decimal> RUT_FUNCIONARIO { get; set; }
        public Nullable<decimal> RUT_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
    }
}
