//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOLETA_CLIENTE> BOLETA_CLIENTE { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<CONTACTO> CONTACTO { get; set; }
        public DbSet<DIA> DIA { get; set; }
        public DbSet<FAMILIA_PRODUCTO> FAMILIA_PRODUCTO { get; set; }
        public DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public DbSet<HORA> HORA { get; set; }
        public DbSet<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
        public DbSet<PERMISO> PERMISO { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<PREGUNTA_SECRETA> PREGUNTA_SECRETA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RUBRO_PROVEEDOR> RUBRO_PROVEEDOR { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<TIPO_ESTADO_PEDIDO> TIPO_ESTADO_PEDIDO { get; set; }
        public DbSet<TIPO_FUNCIONARIO> TIPO_FUNCIONARIO { get; set; }
        public DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VISITAS_WEB> VISITAS_WEB { get; set; }
    
        public virtual int PRC_REG_CLIENTEYUSUARIO(Nullable<decimal> p_RUT, string p_DV, string p_PNOMBRE, string p_SNOMBRE, string p_PAPELLIDO, string p_SAPELLIDO, Nullable<System.DateTime> p_FECHANAC, string p_SEXO, string p_DIRECCION, Nullable<decimal> p_TELEFONO, string p_EMAIL, Nullable<decimal> p_IDCOMUNA)
        {
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            var p_DVParameter = p_DV != null ?
                new ObjectParameter("P_DV", p_DV) :
                new ObjectParameter("P_DV", typeof(string));
    
            var p_PNOMBREParameter = p_PNOMBRE != null ?
                new ObjectParameter("P_PNOMBRE", p_PNOMBRE) :
                new ObjectParameter("P_PNOMBRE", typeof(string));
    
            var p_SNOMBREParameter = p_SNOMBRE != null ?
                new ObjectParameter("P_SNOMBRE", p_SNOMBRE) :
                new ObjectParameter("P_SNOMBRE", typeof(string));
    
            var p_PAPELLIDOParameter = p_PAPELLIDO != null ?
                new ObjectParameter("P_PAPELLIDO", p_PAPELLIDO) :
                new ObjectParameter("P_PAPELLIDO", typeof(string));
    
            var p_SAPELLIDOParameter = p_SAPELLIDO != null ?
                new ObjectParameter("P_SAPELLIDO", p_SAPELLIDO) :
                new ObjectParameter("P_SAPELLIDO", typeof(string));
    
            var p_FECHANACParameter = p_FECHANAC.HasValue ?
                new ObjectParameter("P_FECHANAC", p_FECHANAC) :
                new ObjectParameter("P_FECHANAC", typeof(System.DateTime));
    
            var p_SEXOParameter = p_SEXO != null ?
                new ObjectParameter("P_SEXO", p_SEXO) :
                new ObjectParameter("P_SEXO", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_IDCOMUNAParameter = p_IDCOMUNA.HasValue ?
                new ObjectParameter("P_IDCOMUNA", p_IDCOMUNA) :
                new ObjectParameter("P_IDCOMUNA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_REG_CLIENTEYUSUARIO", p_RUTParameter, p_DVParameter, p_PNOMBREParameter, p_SNOMBREParameter, p_PAPELLIDOParameter, p_SAPELLIDOParameter, p_FECHANACParameter, p_SEXOParameter, p_DIRECCIONParameter, p_TELEFONOParameter, p_EMAILParameter, p_IDCOMUNAParameter);
        }
    }
}
