//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.BOLETA_CLIENTE = new HashSet<BOLETA_CLIENTE>();
        }
    
        public decimal ID { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO { get; set; }
    
        public virtual ICollection<BOLETA_CLIENTE> BOLETA_CLIENTE { get; set; }
    }
}
