//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ESTADO_PEDIDO
    {
        public TIPO_ESTADO_PEDIDO()
        {
            this.ORDEN_PEDIDO = new HashSet<ORDEN_PEDIDO>();
        }
    
        public decimal ID { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
    }
}
