//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.PERSONA = new HashSet<PERSONA>();
            this.PERMISO = new HashSet<PERMISO>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string CLAVE { get; set; }
        public decimal ID_PREGUNTA { get; set; }
        public string RESP_PREGUNTA { get; set; }
    
        public virtual ICollection<PERSONA> PERSONA { get; set; }
        public virtual PREGUNTA_SECRETA PREGUNTA_SECRETA { get; set; }
        public virtual ICollection<PERMISO> PERMISO { get; set; }
    }
}
